# Generated by Django 5.1.4 on 2025-03-31 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockPrice', models.FloatField()),
                ('strikePrice', models.FloatField()),
                ('timeToExpiry', models.IntegerField()),
                ('interestRate', models.FloatField()),
                ('volatility', models.FloatField()),
                ('calcID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('putPrice', models.FloatField()),
                ('callPrice', models.FloatField()),
                ('calcID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.optioninputs')),
            ],
        ),
    ]
