# Generated by Django 5.1.7 on 2025-04-03 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_optionoutputs_calcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_price', models.FloatField()),
                ('strike_price', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('volatility', models.FloatField()),
                ('time_to_maturity', models.FloatField()),
                ('spot_range_min', models.FloatField()),
                ('spot_range_max', models.FloatField()),
                ('vol_range_min', models.FloatField()),
                ('vol_range_max', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='optionoutputs',
            name='calcID',
        ),
        migrations.CreateModel(
            name='OptionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_price', models.FloatField()),
                ('put_price', models.FloatField()),
                ('option_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.optioninput')),
            ],
        ),
        migrations.DeleteModel(
            name='OptionInputs',
        ),
        migrations.DeleteModel(
            name='OptionOutputs',
        ),
    ]
