# Generated by Django 5.1.7 on 2025-07-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_optioninput_remove_optionoutputs_calcid_optionoutput_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optioninput',
            name='spot_range_max',
        ),
        migrations.RemoveField(
            model_name='optioninput',
            name='spot_range_min',
        ),
        migrations.RemoveField(
            model_name='optioninput',
            name='vol_range_max',
        ),
        migrations.RemoveField(
            model_name='optioninput',
            name='vol_range_min',
        ),
        migrations.AddField(
            model_name='optioninput',
            name='price_shock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='optioninput',
            name='volatility_shock',
            field=models.FloatField(null=True),
        ),
    ]
