# Generated by Django 5.2.6 on 2025-09-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_optioninput_spot_range_max_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optioninput',
            unique_together={('spot_price', 'strike_price', 'interest_rate', 'volatility', 'time_to_maturity')},
        ),
    ]
